name: Count Files and Update Jekyll Data

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the workflow on

jobs:
  count_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Choose an appropriate Ruby version

      - name: Execute Ruby Script
        run: ruby generate_file_count.rb

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Update file count"
          git push origin main
